## Email Spam Detection
---------------------------------------------

### About Dataset
- This dataset contains a collection of email text messages, labeled as either spam or not spam. Each email message is associated with a binary label, where "1" indicates that the email is spam, and "0" indicates that it is not spam. The dataset is intended for use in training and evaluating spam email classification models.

- Columns:
    - text (Text): This column contains the text content of the email messages. It includes the body of the emails along with any associated subject lines or headers.
    - spam_or_not (Binary): This column contains binary labels to indicate whether an email is spam or not. "1" represents spam, while "0" represents not spam.

### Import requires libraries

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [20]:
df = pd.read_csv("../../datasets/emails-2.csv")
df.shape

(517401, 2)

In [21]:
df.head()

                       file                                            message
0     allen-p/_sent_mail/1.  Message-ID: <18782981.1075855378110.JavaMail.e...
1    allen-p/_sent_mail/10.  Message-ID: <15464986.1075855378456.JavaMail.e...
2   allen-p/_sent_mail/100.  Message-ID: <24216240.1075855687451.JavaMail.e...
3  allen-p/_sent_mail/1000.  Message-ID: <13505866.1075863688222.JavaMail.e...
4  allen-p/_sent_mail/1001.  Message-ID: <30922949.1075863688243.JavaMail.e...

In [22]:
df.tail()

,file,message
517396,zufferli-j/sent_items/95.,Message-ID: <26807948.1075842029936.JavaMail.e...
517397,zufferli-j/sent_items/96.,Message-ID: <25835861.1075842029959.JavaMail.e...
517398,zufferli-j/sent_items/97.,Message-ID: <28979867.1075842029988.JavaMail.e...
517399,zufferli-j/sent_items/98.,Message-ID: <22052556.1075842030013.JavaMail.e...
517400,zufferli-j/sent_items/99.,Message-ID: <28618979.1075842030037.JavaMail.e...

In [23]:
df.sample(10)

,file,message
44537,campbell-l/inbox/659.,Message-ID: <24960998.1075852933638.JavaMail.e...
160479,hain-m/notes_inbox/752.,Message-ID: <29461024.1075860465030.JavaMail.e...
169109,hernandez-j/sent/159.,Message-ID: <12533932.1075855566256.JavaMail.e...
205670,kaminski-v/all_documents/3285.,Message-ID: <9873851.1075856263110.JavaMail.ev...
482400,taylor-m/notes_inbox/309.,Message-ID: <7559994.1075859990513.JavaMail.ev...
118072,fossum-d/discussion_threads/768.,Message-ID: <10621845.1075842476685.JavaMail.e...
309798,mann-k/all_documents/6614.,Message-ID: <3488380.1075845742569.JavaMail.ev...
265948,lavorato-j/inbox/217.,Message-ID: <26162273.1075862850974.JavaMail.e...
115891,fossum-d/all_documents/116.,Message-ID: <8047964.1075842424943.JavaMail.ev...
205247,kaminski-v/all_documents/2847.,Message-ID: <2081538.1075856252230.JavaMail.ev...

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517401 entries, 0 to 517400
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   file     517401 non-null  object
 1   message  517401 non-null  object
dtypes: object(2)
memory usage: 7.9+ MB

In [25]:
df.isnull().sum()

file       0
message    0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.iloc[0].file

'allen-p/_sent_mail/1.'

In [29]:
df.iloc[0].message

"Message-ID: <18782981.1075855378110.JavaMail.evans@thyme>\nDate: Mon, 14 May 2001 16:39:00 -0700 (PDT)\nFrom: phillip.allen@enron.com\nTo: tim.belden@enron.com\nSubject: \nMime-Version: 1.0\nContent-Type: text/plain; charset=us-ascii\nContent-Transfer-Encoding: 7bit\nX-From: Phillip K Allen\nX-To: Tim Belden <Tim Belden/Enron@EnronXGate>\nX-cc: \nX-bcc: \nX-Folder: \\Phillip_Allen_Jan2002_1\\Allen, Phillip K.\\'Sent Mail\nX-Origin: Allen-P\nX-FileName: pallen (Non-Privileged).pst\n\nHere is our forecast\n\n "